---@enum Airbases
Airbases = {
    Caucasus = {
        Anapa_Vityazevo = "Anapa-Vityazevo",
        Batumi = "Batumi",
        Beslan = "Beslan",
        Gelendzhik = "Gelendzhik",
        Gudauta = "Gudauta",
        Kobuleti = "Kobuleti",
        Krasnodar_Center = "Krasnodar-Center",
        Krasnodar_Pashkovsky = "Krasnodar-Pashkovsky",
        Krymsk = "Krymsk",
        Kutaisi = "Kutaisi",
        Maykop_Khanskaya = "Maykop-Khanskaya",
        Mineralnye_Vody = "Mineralnye Vody",
        Mozdok = "Mozdok",
        Nalchik = "Nalchik",
        Novorossiysk = "Novorossiysk",
        Senaki_Kolkhi = "Senaki-Kolkhi",
        Sochi_Adler = "Sochi-Adler",
        Soganlug = "Soganlug",
        Sukhumi_Babushara = "Sukhumi-Babushara",
        Tbilisi_Lochini = "Tbilisi-Lochini",
        Vaziani = "Vaziani"
    },
    Syria = {
        Abu_al_Duhur = "Abu al-Duhur",
        Adana_Sakirpasa = "Adana Sakirpasa",
        Adiyaman = "Adiyaman",
        Akrotiri = "Akrotiri",
        Al_Qusayr = "Al Qusayr",
        Al_Dumayr = "Al-Dumayr",
        Aleppo = "Aleppo",
        An_Nasiriyah = "An Nasiriyah",
        At_Tanf = "At Tanf",
        Bassel_Al_Assad = "Bassel Al-Assad",
        Beirut_Rafic_Hariri = "Beirut-Rafic Hariri",
        Ben_Gurion = "Ben Gurion",
        Chukurova = "Chukurova",
        Damascus = "Damascus",
        Deir_ez_Zor = "Deir ez-Zor",
        Diyarbakir = "Diyarbakir",
        Ercan = "Ercan",
        Eyn_Shemer = "Eyn Shemer",
        Gaziantep = "Gaziantep",
        Gazipasa = "Gazipasa",
        Gecitkale = "Gecitkale",
        Gulechoba = "Gulechoba",
        H = "H",
        H3 = "H3",
        H3_Northwest = "H3 Northwest",
        H3_Southwest = "H3 Southwest",
        H4 = "H4",
        H4_Emergency = "H4 Emergency",
        Haifa = "Haifa",
        Hama = "Hama",
        Hatay = "Hatay",
        Hatzerim = "Hatzerim",
        Hatzor = "Hatzor",
        Herzliya = "Herzliya",
        Incirlik = "Incirlik",
        Jirah = "Jirah",
        Kahramanmaras = "Kahramanmaras",
        Kedem = "Kedem",
        Khalkhalah = "Khalkhalah",
        Kharab_Ishk = "Kharab Ishk",
        King_Abdullah_II = "King Abdullah II",
        King_Hussein_Air_College = "King Hussein Air College",
        Kingsfield = "Kingsfield",
        Kiryat_Shmona = "Kiryat Shmona",
        Konya = "Konya",
        Kuweires = "Kuweires",
        Lakatamia = "Lakatamia",
        Larnaca = "Larnaca",
        Marj_as_Sultan_North = "Marj as Sultan North",
        Marj_as_Sultan_South = "Marj as Sultan South",
        Marj_Ruhayyil = "Marj Ruhayyil",
        Marka = "Marka",
        Megiddo = "Megiddo",
        Mezzeh = "Mezzeh",
        Minakh = "Minakh",
        Muwaffaq_Salti = "Muwaffaq Salti",
        Naqoura = "Naqoura",
        Nevatim = "Nevatim",
        Nicosia = "Nicosia",
        Palmachim = "Palmachim",
        Palmyra = "Palmyra",
        Paphos = "Paphos",
        Pinarbashi = "Pinarbashi",
        Prince_Hassan = "Prince Hassan",
        Qabr_as_Sitt = "Qabr as Sitt",
        Ramat_David = "Ramat David",
        Rayak = "Rayak",
        Rene_Mouawad = "Rene Mouawad",
        Rosh_Pina = "Rosh Pina",
        Ruwayshid = "Ruwayshid",
        Sanliurfa = "Sanliurfa",
        Sayqal = "Sayqal",
        Shayrat = "Shayrat",
        Tabqa = "Tabqa",
        Taftanaz = "Taftanaz",
        Tal_Siman = "Tal Siman",
        Tel_Nof = "Tel Nof",
        Teyman = "Teyman",
        Tha_lah = "Tha'lah",
        Tiyas = "Tiyas",
        Wujah_Al_Hajar = "Wujah Al Hajar",
        Zarqa = "Zarqa"
    },
    GermanyCW = {
        Wittstock = "Wittstock",
        Altes_Lager = "Altes Lager",
        Barth = "Barth",
        Zerbst = "Zerbst",
        Bremen = "Bremen",
        Briest = "Briest",
        Buckeburg = "Buckeburg",
        Celle = "Celle",
        Cochstedt = "Cochstedt",
        Damgarten = "Damgarten",
        Fassberg = "Fassberg",
        Finow = "Finow",
        Garz = "Garz",
        Gatow = "Gatow",
        Templin = "Templin",
        Gutersloh = "Gutersloh",
        Hamburg = "Hamburg",
        Hamburg_Finkenwerder = "Hamburg Finkenwerder",
        Hannover = "Hannover",
        Laage = "Laage",
        Larz = "Larz",
        Mahlwinkel = "Mahlwinkel",
        Neubrandenburg = "Neubrandenburg",
        Neuruppin = "Neuruppin",
        Peenemunde = "Peenemunde",
        Schonefeld = "Schonefeld",
        Stendal = "Stendal",
        Tegel = "Tegel",
        Tempelhof = "Tempelhof",
        Tutow = "Tutow",
        Werneuchen = "Werneuchen",
        Wunstorf = "Wunstorf",
        Bornholm = "Bornholm",
        Brand = "Brand",
        Brandis = "Brandis",
        Chojna = "Chojna",
        Cologne = "Cologne",
        Dusseldorf = "Dusseldorf",
        Falkenberg = "Falkenberg",
        Heidelberg = "Heidelberg",
        Kastrup = "Kastrup",
        Kiel = "Kiel",
        Landstuhl = "Landstuhl",
        Mainz_Finthen = "Mainz Finthen",
        Sturup = "Sturup",
        Marxwalde = "Marxwalde",
        Nordholz = "Nordholz",
        Norvenich = "Norvenich",
        Oranienburg = "Oranienburg",
        Szczecin_Goleniow = "Szczecin-Goleniow",
        Obermehler_Schlotheim = "Obermehler Schlotheim",
        Adelsheim = "Adelsheim",
        H_FRG_01 = "H FRG 01",
        H_FRG_02 = "H FRG 02",
        H_FRG_03 = "H FRG 03",
        H_FRG_04 = "H FRG 04",
        H_FRG_05 = "H FRG 05",
        H_FRG_06 = "H FRG 06",
        H_FRG_07 = "H FRG 07",
        H_FRG_08 = "H FRG 08",
        H_FRG_09 = "H FRG 09",
        H_FRG_10 = "H FRG 10",
        H_FRG_12 = "H FRG 12",
        H_FRG_13 = "H FRG 13",
        H_FRG_14 = "H FRG 14",
        H_GDR_01 = "H GDR 01",
        H_GDR_02 = "H GDR 02",
        H_GDR_03 = "H GDR 03",
        H_GDR_04 = "H GDR 04",
        H_GDR_05 = "H GDR 05",
        H_GDR_06 = "H GDR 06",
        H_GDR_07 = "H GDR 07",
        H_GDR_08 = "H GDR 08",
        H_GDR_09 = "H GDR 09",
        H_GDR_10 = "H GDR 10",
        H_GDR_11 = "H GDR 11",
        H_FRG_15 = "H FRG 15",
        Revinge = "Revinge",
        Gross_Mohrdorf = "Gross Mohrdorf",
        Lubeck = "Lubeck",
        Kothen = "Kothen",
        Dessau = "Dessau",
        Parchim = "Parchim",
        H_GDR_12 = "H GDR 12",
        Uetersen = "Uetersen",
        Tagra = "Tagra",
        Luneburg = "Luneburg",
        Northeim = "Northeim",
        H_GDR_13 = "H GDR 13",
        H_GDR_14 = "H GDR 14",
        H_GDR_15 = "H GDR 15",
        H_GDR_16 = "H GDR 16",
        H_GDR_17 = "H GDR 17",
        H_FRG_16 = "H FRG 16",
        H_FRG_17 = "H FRG 17",
        H_FRG_18 = "H FRG 18",
        H_FRG_19 = "H FRG 19",
        H_FRG_11 = "H FRG 11",
        Sperenberg = "Sperenberg",
        Uelzen = "Uelzen",
        Dedelow = "Dedelow",
        Kammermark = "Kammermark",
        Weser_Wumme = "Weser Wumme",
        Braunschweig = "Braunschweig",
        Wismar = "Wismar",
        Waren_Vielist = "Waren Vielist",
        Bienenfarm = "Bienenfarm",
        Pinnow = "Pinnow",
        Gardelegen = "Gardelegen",
        Glindbruchkippe = "Glindbruchkippe",
        Ummern = "Ummern",
        Hildesheim = "Hildesheim",
        Verden_Scharnhorst = "Verden-Scharnhorst",
        Rinteln = "Rinteln",
        Holzdorf = "Holzdorf",
        H_Med_GDR_01 = "H Med GDR 01",
        H_Med_GDR_02 = "H Med GDR 02",
        H_Med_GDR_03 = "H Med GDR 03",
        H_GDR_33 = "H GDR 33",
        Airracing_Koblenz = "Airracing Koblenz",
        H_GDR_34 = "H GDR 34",
        Perwenitz = "Perwenitz",
        H_Med_GDR_08 = "H Med GDR 08",
        H_Med_GDR_09 = "H Med GDR 09",
        H_Med_GDR_10 = "H Med GDR 10",
        H_Med_FRG_01 = "H Med FRG 01",
        H_Med_FRG_02 = "H Med FRG 02",
        Sittensen = "Sittensen",
        H_Med_FRG_04 = "H Med FRG 04",
        H_Med_FRG_06 = "H Med FRG 06",
        Sprendlingen = "Sprendlingen",
        Thurland = "Thurland",
        Zollschen = "Zollschen",
        H_Med_FRG_11 = "H Med FRG 11",
        Hasselfelde = "Hasselfelde",
        Grosse_Wiese = "Grosse Wiese",
        H_GDR_18 = "H GDR 18",
        H_FRG_20 = "H FRG 20",
        H_Med_FRG_12 = "H Med FRG 12",
        H_GDR_19 = "H GDR 19",
        H_GDR_30 = "H GDR 30",
        H_Med_GDR_11 = "H Med GDR 11",
        H_FRG_21 = "H FRG 21",
        H_FRG_50 = "H FRG 50",
        H_FRG_23 = "H FRG 23",
        H_FRG_39 = "H FRG 39",
        H_GDR_21 = "H GDR 21",
        H_GDR_22 = "H GDR 22",
        Fritzlar = "Fritzlar",
        Hahn = "Hahn",
        Sembach = "Sembach",
        Allstedt = "Allstedt",
        Zweibrucken = "Zweibrucken",
        Giebelstadt = "Giebelstadt",
        Schweinfurt = "Schweinfurt",
        Haina = "Haina",
        Spangdahlem = "Spangdahlem",
        Frankfurt = "Frankfurt",
        Bindersleben = "Bindersleben",
        Ramstein = "Ramstein",
        Fulda = "Fulda",
        Mendig = "Mendig",
        Merseburg = "Merseburg",
        Wiesbaden = "Wiesbaden",
        Schkeuditz = "Schkeuditz",
        H_Med_GDR_12 = "H Med GDR 12",
        H_Med_GDR_13 = "H Med GDR 13",
        H_Med_GDR_14 = "H Med GDR 14",
        H_Med_GDR_16 = "H Med GDR 16",
        H_GDR_24 = "H GDR 24",
        H_Med_FRG_13 = "H Med FRG 13",
        H_Med_FRG_14 = "H Med FRG 14",
        H_Med_FRG_15 = "H Med FRG 15",
        H_Med_FRG_16 = "H Med FRG 16",
        H_Med_FRG_17 = "H Med FRG 17",
        H_FRG_25 = "H FRG 25",
        H_Radar_GDR_01 = "H Radar GDR 01",
        H_Radar_GDR_02 = "H Radar GDR 02",
        H_Radar_GDR_03 = "H Radar GDR 03",
        H_Radar_GDR_04 = "H Radar GDR 04",
        H_Radar_GDR_05 = "H Radar GDR 05",
        H_Radar_GDR_06 = "H Radar GDR 06",
        H_Radar_GDR_07 = "H Radar GDR 07",
        Bitburg = "Bitburg",
        Airracing_Lubeck = "Airracing Lubeck",
        H_FRG_27 = "H FRG 27",
        Airracing_Frankfurt = "Airracing Frankfurt",
        H_Med_FRG_21 = "H Med FRG 21",
        H_FRG_30 = "H FRG 30",
        H_FRG_31 = "H FRG 31",
        H_FRG_32 = "H FRG 32",
        H_FRG_34 = "H FRG 34",
        H_FRG_51 = "H FRG 51",
        H_FRG_38 = "H FRG 38",
        H_FRG_48 = "H FRG 48",
        H_FRG_49 = "H FRG 49",
        H_Med_FRG_24 = "H Med FRG 24",
        H_Radar_FRG_02 = "H Radar FRG 02",
        H_Med_FRG_26 = "H Med FRG 26",
        H_GDR_25 = "H GDR 25",
        H_GDR_26 = "H GDR 26",
        H_GDR_31 = "H GDR 31",
        H_GDR_32 = "H GDR 32",
        H_Med_FRG_27 = "H Med FRG 27",
        Pferdsfeld = "Pferdsfeld",
        H_Med_FRG_29 = "H Med FRG 29",
        H_FRG_40 = "H FRG 40",
        Buchel = "Buchel",
        Leipzig_Mockau = "Leipzig Mockau",
        H_FRG_43 = "H FRG 43",
        H_FRG_44 = "H FRG 44",
        H_FRG_45 = "H FRG 45",
        H_FRG_46 = "H FRG 46",
        H_FRG_47 = "H FRG 47",
        Bad_Durkheim = "Bad Durkheim",
        Gelnhausen = "Gelnhausen",
        Herrenteich = "Herrenteich",
        Hockenheim = "Hockenheim",
        Langenselbold = "Langenselbold",
        Walldorf = "Walldorf",
        Ober_Morlen = "Ober-Morlen",
        Pottschutthohe = "Pottschutthohe",
        Worms = "Worms",
        H_Radar_GDR_09 = "H Radar GDR 09",
        H_Radar_GDR_08 = "H Radar GDR 08",
        H_FRG_41 = "H FRG 41",
        H_FRG_42 = "H FRG 42"
    }
}

---@enum Theatres
Theatres = {
    CAUCASUS = "Caucasus",
    SYRIA = "Syria",
    CWGERMANY = "GermanyCW"
}

---@enum SAM_TYPES
SAM_TYPES = {
    SHORT_RANGE = "SHORTRANGE",
    MEDIUM_RANGE = "MEDIUMRANGE",
    LONG_RANGE = "LONGRANGE"
}

---@enum ZoneTypes
ZoneTypes = {
    AIRBASE = "AIRBASE",
    STRONGPOINT = "STRONGPOINT",
    FARP = "FARP",
    SAMSITE = "SAMSITE",
    EWSITE = "EWSITE",
    LOGISTICS = "LOGISTICS",
    COMMS = "COMMS",
}

-- Fill in isDefensiveOperation
---@enum AITaskTypes
AITaskTypes = {
    JTAC = "JTAC",
    CAS = "CAS",
    CAP = "CAP",
    INTERCEPT = "INTERCEPT",
    AWACS = "AWACS",
    TANKER = "TANKER",
    SEAD = "SEAD",
    STRIKE = "STRIKE",
    ATTACK_CONVOY = "ATTACK CONVOY",
    CAPTURE_CONVOY = "CAPTURE CONVOY",
    REINFORCEMENT_CONVOY = "REINFORCEMENT CONVOY",
    CAPTURE_HELO = "CAPTURE HELI",
    REINFORCEMENT_HELO = "REINFORCEMENT HELI",
    RESUPPLY_CARGO = "RESUPPLY CARGO",
    RECON = "RECON"
}

---@enum Eras
Eras = {
    WW2 = "WW2",
    EARLYCOLDWAR = "Early Cold War",
    LATECOLDWAR = "Late Cold War",
    MODERN = "Modern"
}

--- Ensure that isOffensiveOperation and isDefensiveOperation in operation manager are complete
---@enum OperationTypes
OperationTypes = {
    CAP = "CAP",
    STRIKE = "Strike",
    SEAD = "SEAD",
    DEAD = "DEAD",
    CAS = "CAS",
    RUNWAY_BOMBING = "Runway Bombing",
    RECON = "Recon",
    AIRDROP = "Airdrop",
    REINFORCEMENT = "Reinforcement",
    STRATEGIC_AIRLIFT = "Airlift",
    INTERCEPT = "Intercept",
    CSAR = "CSAR",
    DEEP_RECON = "Deep Recon",
    DEEP_STRIKE = "Deep strike"
}

---@enum UserAircraftCategories
UserAircraftCategories = {
    HELICOPTER = "helicopter",
    FIXED_WING = "fixed_wing"
}

---@enum TankerRoles
TankerRoles = {
    BOOM = "boom",
    DROGUE = "drogue"
}

---@enum OperationStatus
OperationStatus = {
    AVAILABLE = "available",
    ACTIVE = "active",
    COMPLETED = "completed",
    FAILED = "failed"
}

---@enum CargoCrates
CargoCrates = {
    CDS_BARRELS = "cds_barrels",
    --CDS_CRATES = "cds_crate",
    ContainerClean = "M92_10Ft_Container",
    MOAB = "gbu_43b_airdrop",
    LargeContainer = "iso_container",
    SmallContainer = "iso_container_small",
    SUPPLY_CRATE = "cds_crate"
}

---@enum StockTypes
StockTypes = {
    INITIAL = 1,
    AIR_AIR_LONG_RANGE = 2,
    AIR_AIR_SHORT_RANGE = 3,
    AIR_GROUND_GUIDED_MISSILES = 4,
    AIR_GROUND_GUIDED_BOMBS = 5,
    AIR_GROUND_BOMBS = 6,
    AIR_GROUND_ROCKETS = 7,
    ECM = 8,
    TGP = 9,
    MISC = 10,
    LOGISTICS_CAPTURE = 11,
    AG_AIRCRAFT = 12,
    MULTIROLE_AIRCRAFT = 13,
    AA_AIRCRAFT = 14,
    RECON_AIRCRAFT = 15,
    CARGO_AIRCRAFT = 16,
    FARP = 18,
    CARRIER_INITAL = 19,
    ATTACK_HELICOPTER = 20,
    LOGISTICS_HELICOPTER = 21,
    FARP_MISSILES = 22,
    FARP_AG_ROCKETS = 23,
    FARP_MISC = 24,
    FARP_GUNS = 25,
    FUEL_TANKS = 26
}

MissionLogger = mist.Logger:new("MissionLogger", 3)

--    local base = world.getAirbases()
--    local myBaseTbl = {}
--    for i = 1, #base do
--        local info = {}
--        table.insert(myBaseTbl, Airbase.getTypeName(base[i]))
--    end
--    for i = 1, #env.mission.triggers.zones do
--     env.info(env.mission.triggers.zones[i].name)
-- end
-- -- MissionLogger:info(env.mission.triggers.zones)
-- MissionLogger:info(myBaseTbl)